CREATE TABLE cabinet (
    id INT NOT NULL,
    name NVARCHAR(255) NOT NULL,
    title NVARCHAR(255) NOT NULL,
    type NVARCHAR(255) NOT NULL,
    size NVARCHAR(255) NOT NULL,
    note NVARCHAR(255) NOT NULL,
    status NVARCHAR(255) NOT NULL,
    store_id INT NOT NULL,
    updateTime DATETIMEOFFSET(7) NOT NULL
)
GO
    CREATE NONCLUSTERED INDEX idx_id ON cabinet(id);

GO